### ISSUE TITLE
Update Checker Typo in URL

### ISSUE THREAD

**Issue by Ghawken** [IndigoDomotics/GhostXML#2]
Hi Dave

Think the plugin.py updateChecker code has a typo:  its as below?

self.updater = indigoPluginUpdateChecker.updateChecker(self, "http://indigodomotics.github.io/GhostXML/ghoprostXML_version.html")

Sorry - would pull, update etc - but then would have to deal with github! (and for deleting two characters figured this would be better)

Glenn

**Comment by DaveL17** [comment]
Good eye!  This is fixed and is pushed to the master.  Thanks!
